version: "3"
services:
    node-app:
        build:
            context: .
            args:
                NODE_ENV: development
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - MONGO_USER=admin
            - MONGO_PASSWORD=mypassword
            - SESSION_SECRET=secret
        command: npm run dev
    mongodb:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=mypassword
            
            
    
    
    